CREATE SCHEMA ASEASSIGNMENT2;

CREATE TABLE ASEASSIGNMENT2.USER(
	id INT NOT NULL,
	username VARCHAR(45) NOT NULL,
	password VARCHAR(45) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE(username));

);

INSERT INTO ASEASSIGNMENT2.USER VALUES (1, 'lusi', 'password');
INSERT INTO ASEASSIGNMENT2.USER VALUES (2, 'ray', 'password');
INSERT INTO ASEASSIGNMENT2.USER VALUES (3, 'zerin', 'password');